package dev.techullurgy.chess.events.constants

object BaseEventConstants {
    // CLIENT EVENTS
    const val TYPE_JOIN_ROOM_HANDSHAKE = "TYPE_JOIN_ROOM_HANDSHAKE"
    const val TYPE_SELECTION_FOR_MOVE_DONE = "TYPE_SELECTION_FOR_MOVE_DONE"
    const val TYPE_PIECE_DESTINATION_SELECTION_DONE = "TYPE_PIECE_DESTINATION_SELECTION_DONE"


    // SERVER EVENTS
    const val TYPE_MOVE_DONE = "TYPE_MOVE_DONE"
    const val TYPE_GAME_STARTED = "TYPE_GAME_STARTED"
    const val TYPE_ELAPSED_TIME = "TYPE_ELAPSED_TIME"
    const val TYPE_COLOR_ASSIGNED = "TYPE_COLOR_ASSIGNED"
    const val TYPE_NEXT_MOVE = "TYPE_NEXT_MOVE"

    // SERVER EVENTS
    const val TYPE_GAME_LOADING = "TYPE_GAME_LOADING"
    const val TYPE_GAME_OVER = "TYPE_GAME_OVER"
    const val TYPE_SELECTION_RESULT = "TYPE_SELECTION_RESULT"
    const val TYPE_RESET_SELECTION_DONE = "TYPE_RESET_SELECTION_DONE"
    const val TYPE_GAME_UPDATE = "TYPE_GAME_UPDATE"
    const val TYPE_TIMER_UPDATE = "TYPE_TIMER_UPDATE"
    const val TYPE_SELECTION_DONE = "TYPE_SELECTION_DONE"

    // CLIENT EVENTS
    const val TYPE_ENTER_ROOM_HANDSHAKE = "TYPE_ENTER_ROOM_HANDSHAKE"
    const val TYPE_CELL_SELECTION = "TYPE_CELL_SELECTION"
    const val TYPE_PIECE_MOVE = ""
    const val TYPE_RESET_SELECTION = "TYPE_RESET_SELECTION"
    const val TYPE_DISCONNECT = "TYPE_DISCONNECT"
}